DROP DATABASE IF EXISTS EMPRESAHB;
CREATE DATABASE IF NOT EXISTS EMPRESAHB;
USE EMPRESAHB;

DROP TABLE IF EXISTS EMPREGADOS;
CREATE TABLE IF NOT EXISTS EMPREGADOS(
	NOMBRE VARCHAR(25) NOT NULL,
    APELIDO1 VARCHAR(25) NOT NULL,
    APELIDO2 VARCHAR(25) NULL,
    NSS VARCHAR(15) NOT NULL,
    SALARIO FLOAT NOT NULL,
    DATANACEMENTO DATE NULL,
    SEXO CHAR(1) NOT NULL,
    /*************************/
    PRIMARY KEY(NSS)
)ENGINE INNODB;

DROP TABLE IF EXISTS DEPARTAMENTOS;
CREATE TABLE IF NOT EXISTS DEPARTAMENTOS (
	NUMDEPARTAMENTO INT(11) NOT NULL,
    NOMEDEPARTAMENTO VARCHAR(25) NOT NULL,
    /****************************/
    PRIMARY KEY (NUMDEPARTAMENTO),
    UNIQUE KEY AK_NOMEDEPARTAMENTO (NOMEDEPARTAMENTO)
)ENGINE INNODB;

DROP TABLE IF EXISTS PROXECTOS;
CREATE TABLE IF NOT EXISTS PROXECTOS(
	NUMPROXECTO INT(11) NOT NULL,
    NOMEPROXECTO VARCHAR(25) NOT NULL,
    LUGAR VARCHAR(25) NOT NULL,
    /****************************/
    PRIMARY KEY(NUMPROXECTO),
    UNIQUE KEY AK_NOMPROXECTO(NOMEPROXECTO)
)ENGINE INNODB;